In [3]:
#1. Import the NUMPY package under the name np.

import numpy as np

#2. Print the NUMPY version and the configuration.

print(np.version.version)

1.26.4


In [5]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2, 3, 5))

#4. Print a.

print("Array a:\n", a)

Array a:
 [[[0.38877296 0.03270095 0.72431667 0.34607409 0.15553485]
  [0.62335161 0.39441476 0.44802037 0.11551755 0.19356238]
  [0.74797104 0.81369835 0.71082343 0.58005109 0.60772143]]

 [[0.70997232 0.00472344 0.20697742 0.14203428 0.20999604]
  [0.58789016 0.84248904 0.27672934 0.21104887 0.46858659]
  [0.46749771 0.25274593 0.21294581 0.36734494 0.75052988]]]


In [7]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5, 2, 3))

#6. Print b.

print("Array b:\n", b)

Array b:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [9]:
#7. Do a and b have the same size? How do you prove that in Python code?

print("Do a and b have the same size? ", a.size == b.size)

Do a and b have the same size?  True


In [11]:
#8. Are you able to add a and b? Why or why not?

try:
    a + b
except ValueError as e:
    print("Cannot add a and b because their shapes are incompatible:", e)

Cannot add a and b because their shapes are incompatible: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 


In [13]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = b.transpose(1, 2, 0) 

In [23]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a + c
print("Addition succeeded because shapes now match.")
print("Array d:\n", d)

Addition succeeded because shapes now match.
Array d:
 [[[1.38877296 1.03270095 1.72431667 1.34607409 1.15553485]
  [1.62335161 1.39441476 1.44802037 1.11551755 1.19356238]
  [1.74797104 1.81369835 1.71082343 1.58005109 1.60772143]]

 [[1.70997232 1.00472344 1.20697742 1.14203428 1.20999604]
  [1.58789016 1.84248904 1.27672934 1.21104887 1.46858659]
  [1.46749771 1.25274593 1.21294581 1.36734494 1.75052988]]]


In [17]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print("Array a:\n", a)
print("Array d:\n", d)
print("Relation: d = a + c, where c is an array of ones.")

Array a:
 [[[0.38877296 0.03270095 0.72431667 0.34607409 0.15553485]
  [0.62335161 0.39441476 0.44802037 0.11551755 0.19356238]
  [0.74797104 0.81369835 0.71082343 0.58005109 0.60772143]]

 [[0.70997232 0.00472344 0.20697742 0.14203428 0.20999604]
  [0.58789016 0.84248904 0.27672934 0.21104887 0.46858659]
  [0.46749771 0.25274593 0.21294581 0.36734494 0.75052988]]]
Array d:
 [[[1.38877296 1.03270095 1.72431667 1.34607409 1.15553485]
  [1.62335161 1.39441476 1.44802037 1.11551755 1.19356238]
  [1.74797104 1.81369835 1.71082343 1.58005109 1.60772143]]

 [[1.70997232 1.00472344 1.20697742 1.14203428 1.20999604]
  [1.58789016 1.84248904 1.27672934 1.21104887 1.46858659]
  [1.46749771 1.25274593 1.21294581 1.36734494 1.75052988]]]
Relation: d = a + c, where c is an array of ones.


In [21]:
#12. Multiply a and c. Assign the result to e.

e = a * c
print("Array e:\n", e)

Array e:
 [[[0.38877296 0.03270095 0.72431667 0.34607409 0.15553485]
  [0.62335161 0.39441476 0.44802037 0.11551755 0.19356238]
  [0.74797104 0.81369835 0.71082343 0.58005109 0.60772143]]

 [[0.70997232 0.00472344 0.20697742 0.14203428 0.20999604]
  [0.58789016 0.84248904 0.27672934 0.21104887 0.46858659]
  [0.46749771 0.25274593 0.21294581 0.36734494 0.75052988]]]


In [25]:
#13. Does e equal to a? Why or why not?

print("Does e equal a?", np.array_equal(e, a))

Does e equal a? True


In [27]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print("d_max:", d_max, "d_min:", d_min, "d_mean:", d_mean)

d_max: 1.8424890408444627 d_min: 1.0047234389207644 d_mean: 1.4198014439130084


In [29]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty_like(d)

In [31]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
            else:  # d[i, j, k] == d_mean
                f[i, j, k] = 50

In [33]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

print("Array d:\n", d)
print("Array f:\n", f)

Array d:
 [[[1.38877296 1.03270095 1.72431667 1.34607409 1.15553485]
  [1.62335161 1.39441476 1.44802037 1.11551755 1.19356238]
  [1.74797104 1.81369835 1.71082343 1.58005109 1.60772143]]

 [[1.70997232 1.00472344 1.20697742 1.14203428 1.20999604]
  [1.58789016 1.84248904 1.27672934 1.21104887 1.46858659]
  [1.46749771 1.25274593 1.21294581 1.36734494 1.75052988]]]
Array f:
 [[[ 25.  25.  75.  25.  25.]
  [ 75.  25.  75.  25.  25.]
  [ 75.  75.  75.  75.  75.]]

 [[ 75.   0.  25.  25.  25.]
  [ 75. 100.  25.  25.  75.]
  [ 75.  25.  25.  25.  75.]]]


In [37]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

f_strings = np.empty_like(f, dtype=object)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f_strings[i, j, k] = "A"
            elif d[i, j, k] == d_max:
                f_strings[i, j, k] = "E"
            elif d_min < d[i, j, k] < d_mean:
                f_strings[i, j, k] = "B"
            elif d_mean < d[i, j, k] < d_max:
                f_strings[i, j, k] = "D"
            else:  # d[i, j, k] == d_mean
                f_strings[i, j, k] = "C"

print("Array f with string labels:\n", f_strings)

Array f with string labels:
 [[['B' 'B' 'D' 'B' 'B']
  ['D' 'B' 'D' 'B' 'B']
  ['D' 'D' 'D' 'D' 'D']]

 [['D' 'A' 'B' 'B' 'B']
  ['D' 'E' 'B' 'B' 'D']
  ['D' 'B' 'B' 'B' 'D']]]
